# Generated by Django 4.0.6 on 2022-08-01 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='año',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='auto',
            name='fecha',
            field=models.DateField(default=None, verbose_name=datetime.date.today),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen2',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen3',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen4',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen5',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='imagen6',
            field=models.ImageField(default='adjunte imagen', upload_to='autos/images/'),
        ),
        migrations.AddField(
            model_name='auto',
            name='km',
            field=models.TextField(default='inserte kilometros'),
        ),
        migrations.AddField(
            model_name='auto',
            name='marca',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='auto',
            name='modelo',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='auto',
            name='motor',
            field=models.TextField(default='...'),
        ),
        migrations.AddField(
            model_name='auto',
            name='nombre',
            field=models.CharField(default='inserte nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='auto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='suceso',
            field=models.CharField(default='venta, alquiler o permutacion', max_length=100),
        ),
    ]
